### ISSUE TITLE
fix: inability to login due to missing user role permissions

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#109]
When logging in, the security filter will try and retrieve all permissions from database and convert each to `SimpleGrantedAuthority` through the `ConversionService`. This will fail because I removed that specific conversion (it was a one-liner that only copied a `code` property) but forgot to replace the corresponding method call.

Exact line that throws an exception is:
`org.trebol.security.services.UserDetailsServiceImpl:64`

**Comment by anishsaraogi** [comment]
I would like to work on this issue.

**Comment by bglamadrid** [comment]
> I would like to work on this issue.

Sure! Please do not hesitate to ask me any questions or if you're confused about anything.
