### ISSUE TITLE
test: clean up code resulting from PR #130

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#132]
Comments don't hurt code itself. But when they don't improve readability, they are just garbage.

_Originally posted by @bglamadrid in https://github.com/trebol-ecommerce/spring-boot-backend/pull/130#pullrequestreview-1137442342_
      
I'm raising this issue in regard to all files affected by PR #130, please have a good look at it.
The main requirements are to:

- [ ] Remove all code enclosed within block and line comments
- [ ] Remove all resulting empty methods

**Comment by ashwinpadmakumar** [comment]
@bglamadrid I would like to take up this task. Can you please assign it to me?
