### ISSUE TITLE
Add the new Account Protection to the changelog?

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/spring-boot-backend#137]

**Comment by bglamadrid** [comment]
Yes, I'm going to do some house-keeping and include the most recent changes in there.

I encourage you that in the future you do include your changes to that file when you submit a PR, it isn't mandatory but it sure helps anyway 🤙

I follow [this convention](https://keepachangelog.com/en/1.0.0/) as it is a very simple and fair enough standard IMO.
