### ISSUE TITLE
Write unit tests for `org.trebol.operation.services.CheckoutServiceImpl`

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/spring-boot-backend#143]
From #88 

`CheckoutServiceImpl` should have unit tests that ensure it complies with the interface and methods it implements, `ICheckoutService`.

No need to provide coverage for `private` methods, only the `@Override public` ones from the aforementioned interface.

This interface provides three documented methods.

**Comment by NyorJa** [comment]
hi @mepox @bglamadrid,

Please assign this to me
