### ISSUE TITLE
Write unit tests for `org.trebol.operation.services.ReceiptServiceImpl`

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/spring-boot-backend#146]
From #88 

`ReceiptServiceImpl ` should have unit tests that ensure it complies with the interface and methods it implements, `IReceiptService`.

No need to provide coverage for `private` methods, only the `@Override public` ones from the aforementioned interface.

This interface provides a single method that must fetch receipt information for a given order, given its transaction token (which is created at the beginning of the checkout process).

**Comment by bglamadrid** [comment]
@mepox here you will need to pull and merge (or perhaps rebase) `main` into your local branch too.

**Comment by NyorJa** [comment]
> @mepox here you will need to pull and merge `main` into your local branch too, due to #157.

Regarding on this I think its a good practice to update fork repos everytime if there is an update and then merge locally if PR is raised 😁

**Comment by bglamadrid** [comment]
> Regarding on this I think its a good practice to update fork repos everytime if there is an update and then merge locally if PR is raised 😁

And if any of you find yourselves in trouble while resolving conflicts, you can -and totally should- ask for help. Now you can open a new thread in [Discussions](https://github.com/trebol-ecommerce/spring-boot-backend/discussions) for this 👌

**Comment by bglamadrid** [comment]
@mepox You can use Pojos annotated with builders, but you should refrain of annotate pojos yourself unless you're including them as part of new functionality.

If you have a build or test problem before beginning, you probably are missing the latest changes from `main`, make sure to pull often, and always do it before creating new branches.
