### ISSUE TITLE
Write unit tests for `org.trebol.operation.services.SalesProcessServiceImpl`

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/spring-boot-backend#148]
From #88 

`SalesProcessServiceImpl ` should have unit tests that ensure it complies with the interface and methods it implements, `ISalesProcessService`.

No need to provide coverage for `private` methods, only the `@Override public` ones from the aforementioned interface.

This interface provides three documented methods.

**Comment by bglamadrid** [comment]
Please wait until #157 is done and merged before proceeding with this one...
