### ISSUE TITLE
@Override annotations are missing in Data Controllers in `org.trebol.operation.controllers` [codesmell]

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/spring-boot-backend#169]
Code smell says `@Override` annotations should be used above methods in Data Controllers.

The method is: `readMany(@RequestParam Map<String, String> allRequestParams)`

The Controllers are:

[DataBillingTypesController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataBillingTypesController.java)
[DataCustomersController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataCustomersController.java)
[DataImagesController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataImagesController.java)
[DataPeopleController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataPeopleController.java)
[DataProductCategoriesController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataProductCategoriesController.java)
[DataProductListsController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataProductListsController.java)
[DataProductsController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataProductsController.java)
[DataSalesController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataSalesController.java)
[DataSalespeopleController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataSalespeopleController.java)
[DataSellStatusesController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataSellStatusesController.java)
[DataShippersController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataShippersController.java)
[DataUserRolesController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataUserRolesController.java)
[DataUsersController.java](https://github.com/trebol-ecommerce/spring-boot-backend/blob/main/src/main/java/org/trebol/operation/controllers/DataUsersController.java)

**Comment by bglamadrid** [comment]
Hit me up if you want this assigned @mepox, thanks for reporting it

**Comment by mepox** [comment]
> Hit me up if you want this assigned @mepox, and thanks for reporting it

I will leave it for a bit, in case someone wants it as this is a good first issue.

**Comment by Prashriya** [comment]
Can I work on this issue?

**Comment by mepox** [comment]
Hi @Prashriya ! Sure, go ahead.

@bglamadrid Could you please assign @Prashriya ?
