### ISSUE TITLE
Sonar Issues

### ISSUE THREAD

**Issue by NyorJa** [trebol-ecommerce/spring-boot-backend#170]
Here is the results of sonarscan: [sonarscan](https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&id=trebol-ecommerce_spring-boot-backend)

I would suggest if we divide by category like critical, major, minor

**Comment by bglamadrid** [comment]
Do note that Sonar issues are divided by Bug, Vulnerability, and Code Smell too.

Plus, I wonder if the task of raising issues can be automated?

**Comment by NyorJa** [comment]
> Do note that Sonar issues are categorized by `Bug`, `Vulnerability`, and `Code Smell` too.
> 
> Plus, I wonder if the task of raising issues can be automated from Sonar -> GitHub? That could save us some time before moving on to fixing each one.

yeah...It would be nice so that it will be easy to us to delegate this issues

**Comment by bglamadrid** [comment]
Seems it can't be "automated", but I do can improve the workflow behind it.

I will create two more issue templates

- One of them specifically for "importing" Sonar issues plus linking to them
- Another one to raise test requests in a similar fashion to #161 and others
