### ISSUE TITLE
[Sonar] Add a private constructor to hide the implicit public one - `src/main/java/org/trebol/config/Constants.java`

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#178]
## Summary

- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AYKvHFqAl4ZcazHMfJ5b&open=AYKvHFqAl4ZcazHMfJ5b&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Code Smell`
- Severity: `Major`
- Technical debt: `5min effort`

**Comment by ujwalkumar1995** [comment]
Hey @bglamadrid 
As far as my understanding, if we use the NoArgsConstructor annotation form lombok and mark this class as final, then it should solve the problem.
Let me know if my understanding is correct and I can try to fix this.

**Comment by bglamadrid** [comment]
> Hey @bglamadrid As far as my understanding, if we use the NoArgsConstructor annotation form lombok and mark this class as final, then it should solve the problem. Let me know if my understanding is correct and I can try to fix this.

Making it final could also improve on the concept. But the important bit is to ensure the constructor is private. And `@NoArgsConstructor` does have a way to generate that.

Don't hesitate to submit a PR if you want to, anyway 🙂
