### ISSUE TITLE
[Sonar] Iterate over the "entrySet" instead of the "keySet" in `src/main/java/org/trebol/config/CorsConfigurationSourceBuilder.java`

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#179]
## Summary

- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AYKvHFqnl4ZcazHMfJ5c&open=AYKvHFqnl4ZcazHMfJ5c&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Code Smell`
- Severity: `Major`
- Technical debt: `5min effort`

**Comment by logesr** [comment]
I can work on this issue

**Comment by bglamadrid** [comment]
@logesr Thanks! Please use the Discussions forums if you have any questions or contact me through my e-mail 👍

**Comment by mepox** [comment]
Hi @bglamadrid ! I am not sure if this issue was necessary. This file will be deleted soooon.. see #104

**Comment by bglamadrid** [comment]
@mepox You are correct, but for now it's good to improve on the basics; letting Sonar gives us tips on how to write better code. Also allowing new contributors to step in and contribute with simple tasks.
