### ISSUE TITLE
[Sonar] Reorder the modifiers to comply with the Java Language Specification in `src/main/java/org/trebol/integration/mailing/mailgun/MailgunMailingServiceImpl.java`

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#180]
## Summary

- Source Sonar issue URLs [[1](https://sonarcloud.io/project/issues?issues=AYKvHFn_l4ZcazHMfJ5Z&open=AYKvHFn_l4ZcazHMfJ5Z&id=trebol-ecommerce_spring-boot-backend) | [2](https://sonarcloud.io/project/issues?issues=AYKvHFn_l4ZcazHMfJ5a&open=AYKvHFn_l4ZcazHMfJ5a&id=trebol-ecommerce_spring-boot-backend)]
- Issue type: `Code Smell`
- Severity: `Minor`
- Technical debt: `2min effort`

**Comment by Angel-M-R** [comment]
Could you assing me ? PR ready
