### ISSUE TITLE
[Sonar] Use the primitive boolean expression in `src/main/java/org/trebol/integration/payments/webpayplus/WebpayplusPaymentServiceImpl.java`

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#181]
## Summary

- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AXzM0g8SMzZ3f6e1ClXE&open=AXzM0g8SMzZ3f6e1ClXE&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Code Smell`
- Severity: `Minor`
- Technical debt: `5min effort`

**Comment by Angel-M-R** [comment]
Could you assing me ? PR ready
