### ISSUE TITLE
[Sonar] Change the visibility of this constructor to "protected" in `src/main/java/org/trebol/jpa/services/GenericCrudJpaService.java`

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#182]
## Summary

- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AX2Rz0uU0_sKkZJogP89&open=AX2Rz0uU0_sKkZJogP89&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Code Smell`
- Severity: `Major`
- Technical debt: `5min effort`

**Comment by Angel-M-R** [comment]
Could you assing me ? PR ready
