### ISSUE TITLE
[Sonar] Remove this expression which always evaluates to "true" in `src/main/java/org/trebol/jpa/services/conversion/BillingTypesConverterJpaServiceImpl.java`

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#183]
## Summary

- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AYOr9Y_c0QWdFXn_0wdj&open=AYOr9Y_c0QWdFXn_0wdj&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Code Smell`
- Severity: `Major`
- Technical debt: `10min effort`

**Comment by shivam-Purohit** [comment]
hey @bglamadrid I can take on this issue if you like .

**Comment by bglamadrid** [comment]
@shivam-Purohit Correct, it is pretty much that simple! The Sonar issue itself explains it pretty well I think 🙂 the comparison to null is redundant because `name` has a non-null constraint
