### ISSUE TITLE
[Sonar] Change this condition so that it does not always evaluate to "false" in `src/main/java/org/trebol/jpa/services/conversion/CustomersConverterJpaServiceImpl.java`

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#184]
## Summary

- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AYKvHFl3l4ZcazHMfJ5T&open=AYKvHFl3l4ZcazHMfJ5T&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Bug / Vulnerability / Code Smell`
- Severity: `Blocker / Critical / Major / Minor / Info`
- Technical debt: `5min / 15min / 20min effort`

**Comment by bglamadrid** [comment]
@Angel-M-R

**Comment by Angel-M-R** [comment]
Could you assing me ?
