### ISSUE TITLE
[Sonar] Merge this if statement with the enclosing one in `src/main/java/org/trebol/jpa/services/conversion/PeopleConverterJpaServiceImpl.java`

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#185]
## Summary

- Source Sonar issue URLs [[1](https://sonarcloud.io/project/issues?issues=AX2Rz0tC0_sKkZJogP8x&open=AX2Rz0tC0_sKkZJogP8x&id=trebol-ecommerce_spring-boot-backend) | [2](https://sonarcloud.io/project/issues?issues=AX2Rz0tC0_sKkZJogP8y&open=AX2Rz0tC0_sKkZJogP8y&id=trebol-ecommerce_spring-boot-backend)]
- Issue type: `Code Smell`
- Severity: `Major`
- Technical debt: `5min effort`

**Comment by shivam-Purohit** [comment]
@bglamadrid Can I take on this issue?

**Comment by bglamadrid** [comment]
@shivam-Purohit There's already an open PR on it, #195 

I'd rather have you seek another issue so you don't do a duplicate work 👍
