### ISSUE TITLE
[Sonar] Remove this expression which always evaluates to "true" in `src/main/java/org/trebol/jpa/services/conversion/ProductsConverterJpaServiceImpl.java`

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#186]
## Summary

- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AYKvHFmjl4ZcazHMfJ5X&open=AYKvHFmjl4ZcazHMfJ5X&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Code Smell`
- Severity: `Major`
- Technical debt: `10min`

**Comment by Angel-M-R** [comment]
Hi, can i help with sonar issues ?
