### ISSUE TITLE
[Sonar] Remove this null check which always evaluates to "false" in `src/main/java/org/trebol/jpa/services/conversion/SalespeopleConverterJpaServiceImpl.java`

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/spring-boot-backend#214]
## Summary

- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AYKvHFmTl4ZcazHMfJ5W&open=AYKvHFmTl4ZcazHMfJ5W&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Code Smell`
- Severity: `Major`
- Technical debt: `15min effort`

**Comment by mepox** [comment]
@bglamadrid sourcePerson cannot be null so this null check can be removed, correct?

**Comment by bglamadrid** [comment]
> sourcePerson cannot be null so this null check can be removed, correct?

That is correct 👌

**Comment by bglamadrid** [comment]
> sourcePerson cannot be null so this null check can be removed, correct?

It might be a little trickier. Sonar basically says it is non-null, but suggests that the condition is changed, not removed. Removing it will fix the issue nonetheless, but may also perhaps lead to an issue in the future.

**Comment by mepox** [comment]
@bglamadrid Thank you for your detailed reply! 🥇 

So I should have noticed this:

https://github.com/trebol-ecommerce/spring-boot-backend/blob/3b07112388854b6c7a4003ea2de381ebb12cd2bd/src/main/java/org/trebol/operation/controllers/DataSalespeopleController.java#L71-L77

`@Validated` annotation is missing from the parameter so a `@NonNull` field wouldn't be validated here and could end up being null, right? 😅 

The main reason I was in doubt is what if a pojo, in this case `SalespersonPojo` is created outside of a controller? Then the field(s) wouldn't be validated and a `@NonNull` field could end up being null? So a null check is still necessary?

If this issue is not as simple as removing the expression/null check then I have to say the other issues I just created are probably the same.

**Comment by NyorJa** [comment]
@mepox that is right. We cannot assure if there are non null values during runtime if we are using `nonnull` annotation as @bglamadrid. Maybe we can try `@validated` w/ unit test and I recommend we use mockmvc for that

**Comment by mepox** [comment]
Thanks @NyorJa ! Well in that case we could ignore these issues on Sonar as false positive? OR use StringUtils if we can?
@bglamadrid We already had some closed issues where we removed the null check. I guess they should be added back and/or use StringUtils if possible?

Issue: #183, #184 and #186. Also issue #217 but as @NyorJa suggested, that will use StringUtils.

I close this as false positive.
