### ISSUE TITLE
Use `StringUtils.equals` in expression in `src/main/java/org/trebol/jpa/services/conversion/BillingTypesConverterJpaServiceImpl.java`

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/spring-boot-backend#222]
https://github.com/trebol-ecommerce/spring-boot-backend/blob/3b07112388854b6c7a4003ea2de381ebb12cd2bd/src/main/java/org/trebol/jpa/services/conversion/BillingTypesConverterJpaServiceImpl.java#L61

Thanks @NyorJa

**Comment by NyorJa** [comment]
> Instead of `!name.isBlank()` use `StringUtils.isNotBlank`
> 
> https://github.com/trebol-ecommerce/spring-boot-backend/blob/3b07112388854b6c7a4003ea2de381ebb12cd2bd/src/main/java/org/trebol/jpa/services/conversion/BillingTypesConverterJpaServiceImpl.java#L61

Hi @mepox we can use StringUtils.equals() directly since it can deal on null checking and comparison

**Comment by amaan0o7** [comment]
Hi, @mepox  I'm new to open source. could you assign me this issue I would like to give it a try on this.

**Comment by mepox** [comment]
Hi @amaan0o7 ! @bglamadrid need to confirm if it's ok to work on this as he might do some redesign/refactor..

**Comment by amaan0o7** [comment]
okay @mepox  can you point me to an issue that I can address?

**Comment by bglamadrid** [comment]
Hi @amaan0o7 sorry but this issue is blocked by PR #227
It is likely that this will be resolved once I'm done

**Comment by bglamadrid** [comment]
My suggestion is that you please be patient until #227 is over and closed
After that we'll be counting with a new, tidier, cleaner codebase. Issues should be easier to spot if any one ever raises.

**Comment by mepox** [comment]
> okay @mepox can you point me to an issue that I can address?

@amaan0o7 #225 is a good first issue

**Comment by amaan0o7** [comment]
thanks, @bglamadrid @mepox  I'll look into that one.

**Comment by NyorJa** [comment]
have a good one @amaan0o7

**Comment by bglamadrid** [comment]
This issue is not present in the current version of the `BillingTypesConverterJpaServiceImpl` (since the recent merging of #227), so I'm closing it.
