### ISSUE TITLE
Changes for entity classes

### ISSUE THREAD

**Issue by bglamadrid** [trebol-ecommerce/spring-boot-backend#56]
When I started creating the JPA `@Entity` classes in this project, I was using the NetBeans IDE templates which come with some default annotations. After some study, I've come up with some change proposals to be made to all `@Entity` classes:

* Remove `@Basic()`: used mostly for setting non-nullable columns, but `@Column(boolean optional)` fulfills the same purpose on schema generation and data validation
* Remove `@NamedQuery()`: custom queries is a matter handled much better with Spring Data JPA and QueryDSL
* Remove redundant properties from annotations e.g. if having `@JoinColumn(updatable = true)`, remove the `updatable` property because the default value is true
* Also, make sure all `serialVersionUIDs` are different

**Comment by trangntt-016** [comment]
Hi @bglamadrid , 

Could you please assign this issue to me, I would like to fix it.

**Comment by trangntt-016** [comment]
Please check your email @bglamadrid

**Comment by bglamadrid** [comment]
> Hi @bglamadrid ,
> 
> Could you please assign this issue to me, I would like to fix it.

Alright, go ahead. Hit me up when you create the pull request, or if you have any question. Thank you very much!
